<?php
return [
    'image_formats' => ['jpg', 'png', 'jpge'],
    'default_record' => 20,
    'list_link' => [
        'Abstract' => 'http://iphonewalls.net/abstract/',
        'Animal' => 'http://iphonewalls.net/animals/',
        'Anime' => '',
        'Artistic' => 'http://iphonewalls.net/architecture/',
        'CGI' => '',
        'Cartoon' => '',
        'Celebrity' => '',
        'Comics' => '',
        'Dark' => '',
        'Earth' => '',
        'Fantasy' => '',
        'Food' => 'http://iphonewalls.net/food-drinks/',
        'Humor' => '',
        'Game' => '',
        'Holiday' => '',
        'Man' => 'http://iphonewalls.net/celebrities-guys/',
        'Made' => '',
        'Men' => 'http://iphonewalls.net/celebrities-guys/',
        'Military' => '',
        'Misc' => 'http://iphonewalls.net/misc/',
        'Movie' => 'http://iphonewalls.net/movies/',
        'Multi' => '',
        'Monitor' => '',
        'Music' => 'http://iphonewalls.net/music/',
        'Pattern' => '',
        'Photography' => '',
        'Products' => '',
        'Religious' => '',
        'Sci' => '',
        'FiSportsTV' => 'http://iphonewalls.net/sports/',
        'Show' => '',
        'Technology' => '',
        'Vehicles' => 'http://iphonewalls.net/cars-bikes/',
        'Video' => '',
        'Game' => 'http://iphonewalls.net/games/',
        'Women' => 'http://iphonewalls.net/celebrities-girls/',
        'Weapons' => ''
    ]
];
